# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

 user.security.interactive_login_listener:
        class: UserBundle\EventListner\SecurityListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
        arguments: [ @router, @security.context, @event_dispatcher]

 sg_datatables.user:
        class: UserBundle\Datatables\UserDatatable
        tags:
            - { name: sg.datatable.view }

 sg_datatables.vendor:
         class: VendorBundle\Datatables\VendorDatatable
         tags:
             - { name: sg.datatable.view }

 sg_datatables.group:
         class: EventBundle\Datatables\EventGroupDatatable
         tags:
             - { name: sg.datatable.view }

 sg_datatables.event:
         class: EventBundle\Datatables\EventDatatable
         tags:
             - { name: sg.datatable.view }

 twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }