<?php

namespace EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends EntityRepository
{
    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }
    public function delete($speaker){
        $this->_em->remove($speaker);
        $this->_em->flush();
    }
}
