<?php

namespace EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorRepository extends EntityRepository
{
    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($sponsor){

        $this->_em->remove($sponsor);
        $this->_em->flush();
    }
}
